### ISSUE TITLE
Inclusion of Flairs

### ISSUE THREAD

**Issue by loggerheads-on-binary** [MalloyDelacroix/DownloaderForReddit#210] opened 2021-04-19 22:31 UTC
Could there be a new feature added to allow inclusion of flairs in the filenames/filters? It helps a lot in assortment of the files downloaded.

**Comment by MalloyDelacroix** [comment] 2021-04-23 11:42
Duplicate of #198.  This is slated to be included in the near future.

**Closed by MalloyDelacroix** 2021-04-23 11:42 UTC
Labels: duplicate
