### ISSUE TITLE
soundgasm.net / GWA support (audio)

### ISSUE THREAD

**Issue by Kusurisan** [MalloyDelacroix/DownloaderForReddit#296] opened 2022-08-16 11:57 UTC
It would be cool if Downloader For Reddit could support soundgasm.net / GoneWildAudio Audio Downloads.  
  
To Support it you would have to parse postings for links to soundgasm, and then download the audiofile from there.
Projects like youtube-dl, yt-dlp etc. already support soundgasm.. so it should be relative easy to implement.
it would really be a cool feature to have since there are so many daily posts, that it is difficult to download them all manually by copy pasting each link into youtube-dlg.

**Comment by MalloyDelacroix** [comment] 2022-09-12 11:58
This is a duplicate of #170.

**Closed by MalloyDelacroix** 2022-09-12 11:58 UTC
Labels: duplicate, enhancement
