### ISSUE TITLE
Importing save files and user lists v2.3.2

### ISSUE THREAD

**Issue by ph4nt0mphr34k42** [MalloyDelacroix/DownloaderForReddit#76] opened 2019-11-11 18:20 UTC
On Win7.1, after every update to DFR, I'm greeted with a blank interface and have to manually re-add all my user lists. I'm sure I'm just misisng a step during the upgrade process--probably not a bug--but can anyone help me out with this? It's a pain to re-add hundreds of users over tens of lists. 

Right now I'm updating from v2.2.2 to v2.3.2. 

When I try to "Import Save File" and select \AppData\Roaming\SomeGuySoftware\DownloaderForReddit\save_file.dat, the program asks for permission to overwrite and then crashes (exits). At next start, it gives me the attached message box. "Save Permission Denied: 
A save file could not be created at this location...This likely means the application does not have permission..."
![error](https://user-images.githubusercontent.com/57637644/68610454-ccb81900-0485-11ea-9af1-a30a2cc036b6.png)

Thanks!

**Comment by MalloyDelacroix** [comment] 2019-11-11 18:56
There shouldn't be any additional steps to upgrade.  The import save file function is only intended for when it is necessary to import the save file from another location such as a flash drive, and is really only a convenience method as moving the file manually will accomplish the same thing.

I can't reproduce what you're seeing with a clean save file.  Would it be possible for you to attach your log file?  It can be found in the same location as the save file.

**Comment by ph4nt0mphr34k42** [comment] 2019-11-13 01:28
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/3838971/DownloaderForReddit.log)

Thanks for the quick reply. I'm glad I made a copy of the original .log and .dat files. When the newest version starts up and closes, it wipes the .dat file.

**Comment by MalloyDelacroix** [comment] 2019-11-13 14:05
After looking at your log file, I can see that the problem is related to the peculiarities of the pickle module that this application uses to save data.  It is a known issue that randomly shows up in some systems when users migrate between versions.  This is my "white whale" issue for this application.  I have been trying to fix this problem for a while now, and have as of yet been unsuccessful.  It is one of the reasons that the application is moving to an sqlite back end in the future.

I'm sorry I don't have better news.  If you re-enter the users in the newest version of the app, this should not be a problem going forward.

**Comment by zacker150** [comment] 2020-02-08 03:37
Do you still have the .DAT files?

**Closed** 2020-09-01 11:39 UTC
