### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by thesnyper** [MalloyDelacroix/DownloaderForReddit#10] opened 2018-03-03 08:21 UTC
I have a subreddit list with two groups, "wallpaper" and "wallpapers". Although it has download a combined few thousand files, it keeps crashing whenever I start the download. Log file below ...

{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "03/03/2018 05:39:15 PM", "total_users": 0, "total_subreddits": 32, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "03/03/2018 05:39:15 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "run_subreddit", "lineno": 474, "message": "Subreddit download initiated", "asctime": "03/03/2018 05:39:18 PM", "list_size": 2, "settings": {"imgur_client_valid": true, "restrict_by_score": false, "score_limit_operator": "GREATER", "score_limit": 3000, "subreddit_sort_method": "NEW", "subreddit_sort_top_method": "DAY", "post_limit": 1000, "restrict_by_date": false, "restrict_by_custom_date": false, "custom_date": 86400, "download_videos": true, "download_images": true, "avoid_duplicates": true, "nsfw_filter": "INCLUDE", "save_subreddits_by": "Subreddit Name", "name_downloads_by": "Image/Album Id", "save_directory": "U:/Downloads/Reddit Downloader/", "max_download_thread_count": 4, "save_undownloaded_content": true}}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "start_reddit_extractor_thread", "lineno": 536, "message": "Downloader thread started", "asctime": "03/03/2018 05:39:18 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "03/03/2018 05:39:43 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\DownloadRunner.py\", line 385, in extract\n  File \"DownloaderForReddit\\Core\\RedditObjects.py\", line 195, in load_unfinished_downloads\nTypeError: __init__() missing 1 required positional argument: 'display_only'"}
{"levelname": "INFO", "name": "DownloaderForReddit.Persistence.ObjectStateHandler", "filename": "ObjectStateHandler.py", "module": "ObjectStateHandler", "funcName": "load_pickled_state", "lineno": 83, "message": "Object lists loaded from save file", "asctime": "03/03/2018 05:41:26 PM", "total_users": 0, "total_subreddits": 32, "updated_users": 0, "updated_subreddits": 0}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "load_state", "lineno": 1317, "message": "Save_file successfully loaded into gui", "asctime": "03/03/2018 05:41:26 PM"}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "display_imgur_client_information", "lineno": 1180, "message": "Imgur client info calculated", "asctime": "03/03/2018 05:41:32 PM", "remaining_app_credits": 5567, "remaining_user_credits": 500}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "run_subreddit", "lineno": 474, "message": "Subreddit download initiated", "asctime": "03/03/2018 05:41:57 PM", "list_size": 2, "settings": {"imgur_client_valid": true, "restrict_by_score": false, "score_limit_operator": "GREATER", "score_limit": 3000, "subreddit_sort_method": "NEW", "subreddit_sort_top_method": "DAY", "post_limit": 1000, "restrict_by_date": false, "restrict_by_custom_date": false, "custom_date": 86400, "download_videos": true, "download_images": true, "avoid_duplicates": true, "nsfw_filter": "INCLUDE", "save_subreddits_by": "Subreddit Name", "name_downloads_by": "Image/Album Id", "save_directory": "U:/Downloads/Reddit Downloader/", "max_download_thread_count": 4, "save_undownloaded_content": true}}
{"levelname": "INFO", "name": "DownloaderForReddit.GUI.DownloaderForRedditGUI", "filename": "DownloaderForRedditGUI.py", "module": "DownloaderForRedditGUI", "funcName": "start_reddit_extractor_thread", "lineno": 536, "message": "Downloader thread started", "asctime": "03/03/2018 05:41:57 PM"}
{"levelname": "CRITICAL", "name": "DownloaderForReddit.__main__", "filename": "main.py", "module": "main", "funcName": "log_unhandled_exception", "lineno": 86, "message": "Unhandled exception", "asctime": "03/03/2018 05:42:23 PM", "exc_info": "Traceback (most recent call last):\n  File \"DownloaderForReddit\\Core\\DownloadRunner.py\", line 385, in extract\n  File \"DownloaderForReddit\\Core\\RedditObjects.py\", line 195, in load_unfinished_downloads\nTypeError: __init__() missing 1 required positional argument: 'display_only'"}

**Comment by MalloyDelacroix** [comment] 2018-03-03 17:35
The error here is coming from loading unfinished download items.  Thank you for bringing this to my attention.  This will be fixed for the next patch release.

Unfortunately, looking at the cause of this error, there is no way to salvage the content that is currently saved.  The content will have to be removed from the subreddit objects.  This can be done by  opening the subreddit settings dialog, right clicking the item display list (lower right), setting the list to display saved content, selecting all items in the list, and selecting "Remove Items" from the context menu.

While looking at this error, I found another error with the settings dialog that complicates the removal process.  After you have performed the action above, you will need to click OK without moving on to the next subreddit.  Then reopen the settings dialog box for the next subreddit and delete those content items as well.  You will not be able to see to new content list by clicking on the next subreddit in the subreddit list on the left side of the settings dialog box.  This also will be fixed for the next patch release.

Until the next release, I recommend unselecting "Save undownloaded content" in the settings menu.

**Closed** 2018-03-03 20:16 UTC
