### ISSUE TITLE
Version v3.10.3-beta is loaded with a bunch of viruses

### ISSUE THREAD

**Issue by Deses** [MalloyDelacroix/DownloaderForReddit#239] opened 2021-09-20 14:05 UTC
Version v3.10.3-beta gets flagged by Windows Defender as being infected with the trojan Win32/Skeeyah.

![image](https://user-images.githubusercontent.com/1654959/134016052-e733d0c3-62c0-4782-9af5-68db4b01087c.png)

![image](https://user-images.githubusercontent.com/1654959/134016828-cc02774b-33d8-48c7-b24d-60f0b3677b13.png)
https://www.virustotal.com/gui/file/bd0e3d50a6b0d118f038f594651770704ec225369d5b36bdbdcebbdc9cc4dabf/detection

What the fuck, @MalloyDelacroix?

**Comment by Deses** [comment] 2021-09-20 14:13
![image](https://user-images.githubusercontent.com/1654959/134017369-68a35696-6099-4956-8c14-958ae0568b84.png)


https://www.virustotal.com/gui/file/72b0f2722f25ed4706c90c54133c7949a62e8b8d5c18b0c48025cf25dada45f6

The previous version too.

A Password stealer, oh boy. I guess it's time to start changing passwords.

**Comment by MalloyDelacroix** [comment] 2021-09-20 16:53
Obviously, the application is not "loaded with viruses".  It's an open-source program.  I would have to be an idiot to do that in a repository where literally everyone can see the code.

This is a duplicate of #234.  We believe something is happening when the app is packaged with Pyinstaller that is making windows and others throw false positives.  We're still trying to resolve this.

**Closed by MalloyDelacroix** 2021-09-20 16:53 UTC
Labels: duplicate
