### ISSUE TITLE
Clicking "Imgur Credits" Crashes the Program

### ISSUE THREAD

**Issue by amateurbabes** [MalloyDelacroix/DownloaderForReddit#133] opened 2020-09-05 19:29 UTC
It's as the title says. Clicking Imgur Credits crashes the program. It's the latest beta version.

**Comment by MalloyDelacroix** [comment] 2020-09-06 15:22
Have you entered valid imgur credentials in the imgur section of the settings menu?

**Comment by amateurbabes** [comment] 2020-09-06 16:07
I did not. I feel like that's a bit of an oversight, especially when it crashes if you never checked settings. Maybe just add a pop up saying to check your settings under Imgur would help.

**Comment by MalloyDelacroix** [comment] 2020-09-06 20:14
I agree, it is an oversight.  Without credentials is the only way I could replicate the error, so I just wanted to make sure this was the cause.

**Comment by amateurbabes** [comment] 2020-09-06 22:03
Then all is well.

**Comment by MalloyDelacroix** [comment] 2020-09-08 19:26
Fixed with #139.

**Closed by MalloyDelacroix** 2020-09-08 19:26 UTC
