### ISSUE TITLE
Crash During Downloading

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#27] opened 2018-07-23 20:29 UTC
Happens sometimes randomly, happens more if you have more than 1 download thread set.
Steps:
1-click download
2-while downloading crash sometimes occurs randomly

Version: 2.3.0-master commit: 4a321df5fe9a72e7f778e7799aca0ff4fcf21dcf
Python: 3.7.0-windows

Screenshot:
https://imgur.com/a/w1S4bC2

**Comment by MalloyDelacroix** [comment] 2018-07-24 00:01
This is a duplicate of issue #21.  I am still looking into a solution for this one.

**Closed by MalloyDelacroix** 2018-07-24 00:01 UTC
Labels: duplicate
