### ISSUE TITLE
Performance Slowdowns

### ISSUE THREAD

**Issue by Chrisnetika** [MalloyDelacroix/DownloaderForReddit#36] opened 2018-08-07 11:51 UTC
I generally notice with these new commits the general performance slowdowns when downloading, takes much longer to extract than usual.Would like to see some speedups in the future.Perhaps SQL-lite backend and more efficient processing on the part of the extractors. from  commit 55e87899ec9da4cf73714674d8aa2e3123d8ea50 to 3ec6f1ea96da65cb5337dfdce46940069fa5b683 is a noticable difference

**Comment by MalloyDelacroix** [comment] 2018-08-07 15:56
The performance difference between those two commits is because of the introduction of rate limiters for extractors.  I was beginning to see a lot of rate limit error responses from servers, so this was intended to fix this.  I will look at reworking this system.

A SQLite storage system is in the plan for the future.  It will be introduced in version 3.0.  I have some other projects going at the moment and that will be a very large update to the platform, so it is likely not going to happen until 2019.  Any current interactions that will be handled by sqlite are now handled by python objects in memory.  The sqlite backend will likely not  see any performance improvements.  It will mostly be to support new features.

**Comment by MalloyDelacroix** [comment] 2018-08-13 16:15
I have removed the rate limiter.  Since there were no other reports of rate limit errors I decided I shouldn't try to fix problems that didn't exist.  That should have been the only thing affecting performance in the newer commits.

**Closed by MalloyDelacroix** 2018-08-13 16:15 UTC
