### ISSUE TITLE
Does not download after first Download - again

### ISSUE THREAD

**Issue by SomeRandomDude870** [MalloyDelacroix/DownloaderForReddit#168] opened 2020-10-29 21:43 UTC
Describe the bug
No matter which sub, after I have downloaded from a sub once, I am unable to download from there again.
Doesn´t matter what subreddit. 
And yes, I have removed the "Date Limit".

Environment Information
    Win10 pro
    3.2.2b
    release

To Reproduce (optional)
add a subreddit
download from it
stop or wait until done
remove "date limit"
try to download again.

For all but the most trivial of issues, please attach the latest log file.
where is it?

**Comment by MalloyDelacroix** [comment] 2020-10-30 11:46
Duplicate of #149.

**Closed by MalloyDelacroix** 2020-10-30 11:46 UTC
Labels: duplicate
