### ISSUE TITLE
can't download redgifs.com

### ISSUE THREAD

**Issue by heppphepp** [MalloyDelacroix/DownloaderForReddit#216] opened 2021-05-16 09:28 UTC
can't download redgifs.com 

plz help

and Not included supported_video_sites

**Comment by MalloyDelacroix** [comment] 2021-05-16 13:36
This is a duplicate of #212.

Can you attach your log file?  If you don't want to attach it, you can send it privately to downloaderforreddit@gmail.com.

**Closed by MalloyDelacroix** 2021-05-16 13:36 UTC
Labels: duplicate

**Comment by heppphepp** [comment] 2021-05-21 06:37
[DownloaderForReddit.log](https://github.com/MalloyDelacroix/DownloaderForReddit/files/6520585/DownloaderForReddit.log)
