### ISSUE TITLE
UNEXPLAINED CRASH E SOME PROBLEM

### ISSUE THREAD

**Issue by vincenzogianfelice** [MalloyDelacroix/DownloaderForReddit#206] opened 2021-03-11 15:44 UTC
In the last release (3.8.0) suddenly, pressing the right button in the user pane, the application closes. So I tried to download the previous version and this doesn't happen. But there are other problems!
For example, while I'm downloading and right clicking on any user, the application stops responding! Also I have to say that the user interface is a real mess ... you don't understand much and it's very complicated in my opinion. Also, where does the application store the DB? And then, why is there a limit of 1000 posts (maximum) to download? If you are downloading a user it should be ALL the user's posts ... if the user has more than 1000 posts how do we do it? This application needs improvement, starting from the graphical interface. I hope you will take note of all of this.

I tried the application on windows 10 pro x64

**Comment by MalloyDelacroix** [comment] 2021-03-11 19:21
The crashing on right click of an empty user/subreddit field is a duplicate issue of #196.  It was fixed by pull request #195, although it is an unreleased change at the moment. 

I can't reproduce the crashing that occurs when right-clicking a list while a download is in progress.  This could be an issue from the previous version you mentioned downloading, which has since been fixed.

The 1,000 post limit is an API limit in place by reddit.  I don't have any control over this, and there is no way to fetch more posts than that while using the reddit API.

The database location is under "C:/Users/User/AppData/Roaming/SomeGuySoftware/DownloaderForReddit".  You can access this easily from the app by going to the File menu, then clicking "Open Data Directory".

I'm not a UI designer by any means, and there will be a user manual before the new version is out of beta, which may help with the UI confusion.  Is there an area of the UI that you found particularly difficult to understand?

**Closed** 2021-03-17 11:42 UTC
