### ISSUE TITLE
Stopping Download blocks UI

### ISSUE THREAD

**Issue by SomeRandomDude870** [MalloyDelacroix/DownloaderForReddit#148] opened 2020-09-27 22:04 UTC
**Describe the bug**
When I am downloading something and then stop it, the UI basically freezes. I get the "Warning: Stopped". The timer under the download field keeps running. I am able very slowly to open the Menus, but when I do that basically my whole PC freezes.
After that I have to close the program via Task manager.
This happens after the Downloader produces "Error" messages. When there are no error messages and everything empty until "warning" then it stops normally.

**Environment Information**
 - Win10 pro
 - 3.2.1b
 - release

**To Reproduce** (optional)
Download a single Subreddit and then stop it...

**For all but the most trivial of issues, please attach the latest log file.**
Well, where is the log path?
------------------------------------------------------------------------------------------------------------

**Note:** All issues marked with the **Information Needed** label will be closed after 30 days if no information is provided.

**Comment by MalloyDelacroix** [comment] 2020-09-28 17:48
Does the same thing happen when you click terminate download as opposed to just stopping it?

**Comment by SomeRandomDude870** [comment] 2020-09-28 21:34
yes, it too slows down the UI.

**Comment by MalloyDelacroix** [comment] 2021-07-17 14:29
Is this still a persistent issue?  I cannot reproduce this behavior.  It's possible that it has been inadvertently fixed as a side effect to another bug fix between your comment and now.

**Comment by MalloyDelacroix** [comment] 2022-01-29 21:46
There hasn't been any activity on this issue in a while, and I was never able to reproduce it.  So I'm going to close it.

**Closed by MalloyDelacroix** 2022-01-29 21:46 UTC
